// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace IT_05.Server.Models;

public partial class IT_05Context : DbContext
{
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
        => optionsBuilder.UseSqlServer("Data Source=localhost\\SQLEXPRESS;Initial Catalog=IT_05;Integrated Security=True;Persist Security Info=False;Pooling=False;MultipleActiveResultSets=False;Encrypt=True;TrustServerCertificate=True;Command Timeout=0");


    public virtual DbSet<queue> queues { get; set; }

    public virtual DbSet<ticket> tickets { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<queue>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__queues__3213E83FBC0E7AE4");

            entity.Property(e => e.queue_number)
                .IsRequired()
                .HasMaxLength(100);
        });

        modelBuilder.Entity<ticket>(entity =>
        {
            entity.HasKey(e => e.id).HasName("PK__tickets__3213E83F2DEC35F7");

            entity.HasIndex(e => new { e.queue_id, e.created_at }, "IX_Tickets_ActiveQueue").HasFilter("([status]='PENDING')");

            entity.Property(e => e.created_at).HasDefaultValueSql("(sysdatetimeoffset())");
            entity.Property(e => e.status)
                .HasMaxLength(20)
                .HasDefaultValue("PENDING");

            entity.HasOne(d => d.queue).WithMany(p => p.tickets)
                .HasForeignKey(d => d.queue_id)
                .HasConstraintName("FK_Tickets_Queues");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}