// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IT_05.Server.Models;

public partial class queue
{
    public int id { get; set; }

    public string queue_number { get; set; }

    public virtual ICollection<ticket> tickets { get; set; } = new List<ticket>();
}