// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace IT_05.Server.Models;

public partial class ticket
{
    public long id { get; set; }

    public int queue_id { get; set; }

    public string status { get; set; }

    public DateTimeOffset? created_at { get; set; }

    public virtual queue queue { get; set; }
}